const DentryItem = require("./dentryItem");
const {getDocList, getSpaceInfo} = require("../api");
const {dalert} = require("./dialog");
const DingTalkDomain = "alidocs.dingtalk.com";


module.exports = {
    render(h) {
        return h("div", {}, [
            h("div", {class: "label px-0"}, [
                h("div", {ref:"progressTip", class: "label-text"}, "我的文档"),
                h("div", {ref: "btnArea", class: "label-text"}, [
                    h("a", {ref: "downloadBtn", class: "link text-accent hidden", on: {click: this.onDownloadClick}}, "下载选中"),
                    h("a", {ref: "reloadBtn", class: "link text-accent hidden", on: {click: this.reload}}, "重新加载")
                ])
            ]),
            h("div", {class: "overflow-auto", style: {maxHeight: "700px"}}, [
                h("progress", {ref: "progress", class: "progress"}, []),
                h("ul", {ref: "list", class: "menu menu-xs bg-base-200 rounded-lg w-full hidden"}, this.dentrys.map(dentryInfo => {
                    return h("DentryItem", {ref: "di", props: () => ({dentryInfo: dentryInfo}), on: {selectChange: this.onDentrySelectChange}})
                }))
            ])
        ])
    },
    components: {
        DentryItem
    },
    created () {
    },
    mounted() {
        this.readCurrentPage();

        // setTimeout(() => {
        //     this.addDentry({
        //         "bizSceneCode":2,
        //         "children":[
        //             {
        //                 "bizSceneCode":2,
        //                 "bizSceneId":"185916079",
        //                 "cleaned":false,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1616262033000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"f-4565995482-0",
        //                 "dentryKey":"QO3pJDh4rBnyY64o",
        //                 "dentryStatistic":{
        //                     "childrenCount":1
        //                 },
        //                 "dentryType":"folder",
        //                 "dentryUuid":"RK5NZQYprEoWo3Qr1qNcaW1waOeDkXlj",
        //                 "depth":1,
        //                 "driveDentryId":"0",
        //                 "driveSceneType":"hideOrgEmp",
        //                 "driveSpaceId":"4565995482",
        //                 "extraDTO":{
        //
        //                 },
        //                 "hasChildren":true,
        //                 "isInTrash":false,
        //                 "isSystem":true,
        //                 "name":"我的文件（来自钉盘）",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "path":"/我的文件（来自钉盘）",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"4565995482",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "systemFileType":1,
        //                 "thumbnail":"",
        //                 "updatedTime":1628872578000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "dentryActions":[
        //                         "COPY_DENTRY",
        //                         "GET_DENTRY_MEMBER",
        //                         "GET_DENTRY",
        //                         "DELETE_DENTRY",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "UPLOAD_FOLDER",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "CREATE_CHILD",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "UPLOAD",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "contentType":"document",
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1717568726000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"0VzgQDpKq9rr0mJe",
        //                 "dentryKey":"dzXAO834kcn7eXxB",
        //                 "dentryStatistic":{
        //                     "childrenCount":0,
        //                     "previewCount":15
        //                 },
        //                 "dentryType":"file",
        //                 "dentryUuid":"QG53mjyd80yPb1kGcGQpv5MqW6zbX04v",
        //                 "depth":1,
        //                 "driveDentryId":"142246405934",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "extension":"xlsx",
        //                 "fileSize":14655,
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":false,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"最近执行的指令的所属业务/系统/部门.xlsx",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:-1638392.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"$iAELAqNqcGcDAQTNAooFzQHWBtoAI4QBpCEr19sCqqQE_RgD69oCX7IDzwAAAY_nP3m6BM4CyQ_oBwAIAA",
        //                 "updatedTime":1717571702000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "version":69,
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "DOWNLOAD_ATTACHMENT",
        //                         "COPY_DENTRY",
        //                         "SAVE_AS_TEMPLATE",
        //                         "GET_DENTRY_MEMBER",
        //                         "EXPORT",
        //                         "DOWNLOAD",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "EDIT_HISTORY",
        //                         "SEND_COPY_FILE",
        //                         "UPLOAD_ATTACHMENT",
        //                         "GET_DENTRY",
        //                         "EDIT",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "EXPORT_IMAGE",
        //                         "READ_HISTORY",
        //                         "CONTENT_COPY",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW",
        //                         "CLOUD_PRINT"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "contentType":"alidoc",
        //                 "contentUpdatedTime":1706602648175,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1706602313000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"0VzgQ7dq20BjZmJe",
        //                 "dentryKey":"ROwoBXjYnTAZO3me",
        //                 "dentryStatistic":{
        //                     "childrenCount":0
        //                 },
        //                 "dentryType":"file",
        //                 "dentryUuid":"Obva6QBXJw6pry1YCbEY7KvRVn4qY5Pr",
        //                 "depth":1,
        //                 "docKey":"WgZOZwDxeMZQlLX8",
        //                 "driveDentryId":"130324127279",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "extension":"axls",
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":false,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"自动化组春节请假明细.axls",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:-1572856.0",
        //                 "protocolVersion":1,
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"$iAELAqNqcGcDAQTNAmwFzQHABtoAI4QBpCEz9hcCqiy9DuLiBZA6RuwDzwAAAY1ZcxNIBM4AkOu0BwAIAA",
        //                 "updatedTime":1706602648000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQDPM5lG-IIeSlHNBB3NBB2wtO3t0iYud0YF3eF9YXTVAA",
        //                     "loginUserType":0,
        //                     "name":"林含",
        //                     "uid":"625745907"
        //                 },
        //                 "url":{
        //                     "mobileChildAppUrl":"https://alidocs.dingtalk.com/spreadsheetv2/ROwoBXjYnTAZO3me/edit?dt_editor_toolbar=true&biz_ver=10&docId=WgZOZwDxeMZQlLX8&from=dingnote&dd_user_keyboard=false&utm_scene=person_space&mainsiteOrigin=mainsite&workspaceId=0VzgQ7dq20BjZmJe&docKey=WgZOZwDxeMZQlLX8&dentryKey=ROwoBXjYnTAZO3me&type=s#preview=false",
        //                     "pcChildAppPreviewUrl":"https://alidocs.dingtalk.com/spreadsheetv2/ROwoBXjYnTAZO3me/view?dt_editor_toolbar=true&biz_ver=10&docId=WgZOZwDxeMZQlLX8&from=dingnote&dd_user_keyboard=false&utm_scene=person_space&mainsiteOrigin=mainsite&workspaceId=E0VzgyD5ylldmJep&docKey=WgZOZwDxeMZQlLX8&dentryKey=ROwoBXjYnTAZO3me#preview=true",
        //                     "pcChildAppUrl":"https://alidocs.dingtalk.com/spreadsheetv2/ROwoBXjYnTAZO3me/edit?dt_editor_toolbar=true&biz_ver=10&docId=WgZOZwDxeMZQlLX8&from=dingnote&dd_user_keyboard=false&utm_scene=person_space&mainsiteOrigin=mainsite&workspaceId=E0VzgyD5ylldmJep&docKey=WgZOZwDxeMZQlLX8&dentryKey=ROwoBXjYnTAZO3me#preview=false"
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "DOWNLOAD_ATTACHMENT",
        //                         "COPY_DENTRY",
        //                         "SAVE_AS_TEMPLATE",
        //                         "GET_DENTRY_MEMBER",
        //                         "EXPORT",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "UPLOAD_ATTACHMENT",
        //                         "GET_DENTRY",
        //                         "EDIT",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "EXPORT_IMAGE",
        //                         "CREATE_CHILD",
        //                         "CONTENT_COPY",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1692081071000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"E0Vzgx7lyAE1dXJe",
        //                 "dentryKey":"pkb7BJOaWcMVNe8Q",
        //                 "dentryStatistic":{
        //                     "childrenCount":1
        //                 },
        //                 "dentryType":"folder",
        //                 "dentryUuid":"mExel2BLV5y3b1Z6cxEwPopYVgk9rpMq",
        //                 "depth":1,
        //                 "driveDentryId":"113112754852",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":true,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"课件",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:-1376248.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"",
        //                 "updatedTime":1692081071000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "COPY_DENTRY",
        //                         "GET_DENTRY_MEMBER",
        //                         "GET_DENTRY",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "UPLOAD_FOLDER",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "CREATE_CHILD",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "UPLOAD",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1682587992000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"E0Vzg341JvA40zJe",
        //                 "dentryKey":"pJ2mGE5yNiboO3nP",
        //                 "dentryStatistic":{
        //                     "childrenCount":5
        //                 },
        //                 "dentryType":"folder",
        //                 "dentryUuid":"XPwkYGxZV3yNbY2ocjD2w1bM8AgozOKL",
        //                 "depth":1,
        //                 "driveDentryId":"103139747657",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":true,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"意见稿、方案搞",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:-1310712.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"",
        //                 "updatedTime":1692065164000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "COPY_DENTRY",
        //                         "GET_DENTRY_MEMBER",
        //                         "GET_DENTRY",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "UPLOAD_FOLDER",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "CREATE_CHILD",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "UPLOAD",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1675997303000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"E0Vzg46yB0AKAXJe",
        //                 "dentryKey":"RxPBPgYyBSJ1e40z",
        //                 "dentryStatistic":{
        //                     "childrenCount":19
        //                 },
        //                 "dentryType":"folder",
        //                 "dentryUuid":"lDZEN6or0dp8ZxnxG1PnVaPYQK91xzy3",
        //                 "depth":1,
        //                 "driveDentryId":"96033618658",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":true,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"工作目录",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:-1245176.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"",
        //                 "updatedTime":1675997307000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "COPY_DENTRY",
        //                         "GET_DENTRY_MEMBER",
        //                         "GET_DENTRY",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "UPLOAD_FOLDER",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "CREATE_CHILD",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "UPLOAD",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1675997319000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"E0Vzg4lZQ6o5JXJe",
        //                 "dentryKey":"RqgWgG1oJiwxoL21",
        //                 "dentryStatistic":{
        //                     "childrenCount":2
        //                 },
        //                 "dentryType":"folder",
        //                 "dentryUuid":"lo1YvX0prG98kyAyLEm5VPw7xzbmLdEZ",
        //                 "depth":1,
        //                 "driveDentryId":"96033674153",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":true,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"研究报告文档",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:-1179640.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"",
        //                 "updatedTime":1675997334000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "COPY_DENTRY",
        //                         "GET_DENTRY_MEMBER",
        //                         "GET_DENTRY",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "UPLOAD_FOLDER",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "CREATE_CHILD",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "UPLOAD",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1651907216000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"E0VzgPPwowdy7XJe",
        //                 "dentryKey":"RbbEJP1mYhkwgGxm",
        //                 "dentryStatistic":{
        //                     "childrenCount":3
        //                 },
        //                 "dentryType":"folder",
        //                 "dentryUuid":"mM3zoYAw1Rr8DqZ4ew56WnZ07y9NpXxD",
        //                 "depth":1,
        //                 "driveDentryId":"58722880104",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":true,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"我的需求",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:-327672.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"",
        //                 "updatedTime":1651907221000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "COPY_DENTRY",
        //                         "GET_DENTRY_MEMBER",
        //                         "GET_DENTRY",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "UPLOAD_FOLDER",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "CREATE_CHILD",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "UPLOAD",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1648201646000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"E0Vzg7Rpa9540zJe",
        //                 "dentryKey":"RVMvwYXkVh4K23Gx",
        //                 "dentryStatistic":{
        //                     "childrenCount":2
        //                 },
        //                 "dentryType":"folder",
        //                 "dentryUuid":"jkB7yl4ZK3vV6Kl9Ndj6JPMX2O6oxqw0",
        //                 "depth":1,
        //                 "driveDentryId":"55201171284",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":true,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"测试岗",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:64.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"",
        //                 "updatedTime":1648201653000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "COPY_DENTRY",
        //                         "GET_DENTRY_MEMBER",
        //                         "GET_DENTRY",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "UPLOAD_FOLDER",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "CREATE_CHILD",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "UPLOAD",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1646451223000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"E0Vzg5jbAxlMJmJe",
        //                 "dentryKey":"RNq8GeN00IwDO3A9",
        //                 "dentryStatistic":{
        //                     "childrenCount":6
        //                 },
        //                 "dentryType":"folder",
        //                 "dentryUuid":"mdvQnONayjBJKY3oeannWPY2MeXzp5o0",
        //                 "depth":1,
        //                 "driveDentryId":"53523883288",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "finalizeInfo":{
        //                     "enableFinalize":false
        //                 },
        //                 "hasChildren":true,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"自动化组面试提和考核测试",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:128.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "roleId":"1000",
        //                     "scope":1
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"",
        //                 "updatedTime":1715320358000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "COPY_DENTRY",
        //                         "GET_DENTRY_MEMBER",
        //                         "GET_DENTRY",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "UPLOAD_FOLDER",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "CREATE_CHILD",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "UPLOAD",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             },
        //             {
        //                 "ancestorList":[],
        //                 "bizSceneCode":2,
        //                 "contentType":"alidoc",
        //                 "contentUpdatedTime":1642151581989,
        //                 "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //                 "createdTime":1642151205000,
        //                 "creator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "dentryId":"E0Vzgex4OqrndmJe",
        //                 "dentryKey":"RV45oVM5oc4K23Gx",
        //                 "dentryStatistic":{
        //                     "childrenCount":0
        //                 },
        //                 "dentryType":"file",
        //                 "dentryUuid":"jkB7yl4ZK3vV6PYo6KYo8PMX2O6oxqw0",
        //                 "depth":1,
        //                 "docKey":"AmPdnp6xPxw6Ow98",
        //                 "driveDentryId":"50661666140",
        //                 "driveParentDentryId":"37483966289",
        //                 "driveSceneType":"orgBizMeta",
        //                 "driveSpaceId":"2823535130",
        //                 "extension":"adoc",
        //                 "fileSize":257359,
        //                 "finalizeInfo":{
        //                     "enableFinalize":true
        //                 },
        //                 "hasChildren":false,
        //                 "illegal":false,
        //                 "isInTrash":false,
        //                 "name":"术语、专有名词及含义.adoc",
        //                 "orgId":"93255011",
        //                 "parentDentryId":"JaYr98zn2zLxnd6W",
        //                 "parentDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                 "positionCursor":"pos:2048.0",
        //                 "securityInfo":{
        //                     "forbiddenCopy":{
        //                         "isInherit":true,
        //                         "name":"forbiddenCopy",
        //                         "value":false
        //                     },
        //                     "forbiddenSpread":{
        //                         "isInherit":true,
        //                         "name":"forbiddenSpread",
        //                         "value":false
        //                     },
        //                     "watermark":{
        //                         "isInherit":false,
        //                         "name":"watermark",
        //                         "value":false
        //                     }
        //                 },
        //                 "shareScopeInfo":{
        //                     "scope":0
        //                 },
        //                 "spaceId":"E0VzgyD5ylldmJep",
        //                 "spaceProfile":{
        //                     "createdTime":1624848955461,
        //                     "description":"",
        //                     "driveSpaceId":"2823535130",
        //                     "icon":"",
        //                     "id":"E0VzgyD5ylldmJep",
        //                     "name":"mine space",
        //                     "owner":{
        //                         "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                         "name":"范雪蛟",
        //                         "uid":"185916079"
        //                     },
        //                     "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //                     "type":2,
        //                     "updatedTime":1717571647394
        //                 },
        //                 "thumbnail":"$iAEKAqNqcGcDAQTNAmwFzQHABtoAI4QBpCEEHBgCquNAqwlEtX342WQDzwAAAX5X3g8nBM4AUtafBwAIAA",
        //                 "updatedTime":1642151248000,
        //                 "updator":{
        //                     "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                     "loginUserType":0,
        //                     "name":"范雪蛟",
        //                     "uid":"185916079"
        //                 },
        //                 "url":{
        //                     "mobileChildAppUrl":"https://alidocs.dingtalk.com/h5/d?dt_editor_toolbar=true&biz_ver=10&showCommentPanel=false&dd_user_keyboard=false&dd_full_screen=true&dontjump=true&mainsiteOrigin=mainsite&dentryKey=RV45oVM5oc4K23Gx&type=d#/edit?dentryKey=RV45oVM5oc4K23Gx",
        //                     "pcChildAppPreviewUrl":"https://alidocs.dingtalk.com/note/preview?dt_editor_toolbar=true&biz_ver=10&docId=AmPdnp6xPxw6Ow98&docType=doc&dontjump=true&utm_scene=person_space&platform=pc&mainsiteOrigin=mainsite&showCommentPanel=false&from=dingnote&dd_user_keyboard=false&dd_full_screen=true&workspaceId=E0VzgyD5ylldmJep&docKey=AmPdnp6xPxw6Ow98&dentryKey=RV45oVM5oc4K23Gx#preview=true",
        //                     "pcChildAppUrl":"https://alidocs.dingtalk.com/note/edit?dt_editor_toolbar=true&biz_ver=10&docId=AmPdnp6xPxw6Ow98&docType=doc&dontjump=true&utm_scene=person_space&platform=pc&mainsiteOrigin=mainsite&showCommentPanel=false&from=dingnote&dd_user_keyboard=false&dd_full_screen=true&workspaceId=E0VzgyD5ylldmJep&docKey=AmPdnp6xPxw6Ow98&dentryKey=RV45oVM5oc4K23Gx#preview=false"
        //                 },
        //                 "visitorRelatedInfo":{
        //                     "collaboratorRoleId":"5000",
        //                     "dentryActions":[
        //                         "DOWNLOAD_ATTACHMENT",
        //                         "COPY_DENTRY",
        //                         "SAVE_AS_TEMPLATE",
        //                         "GET_DENTRY_MEMBER",
        //                         "EXPORT",
        //                         "MANAGE_DENTRY_MEMBER",
        //                         "DELETE_DENTRY",
        //                         "IMPORT",
        //                         "CHANGE_PERMISSION_MODE",
        //                         "PUBLIC_SHARE",
        //                         "IMPORT_FOLDER",
        //                         "LINK_SHARE",
        //                         "LIST_CHILD",
        //                         "SAVE_AS",
        //                         "TEMPORARY_SHARE_NODE",
        //                         "RECYCLE_DENTRY",
        //                         "UPLOAD_ATTACHMENT",
        //                         "EXPORT_CLOUD",
        //                         "GET_DENTRY",
        //                         "EDIT",
        //                         "DOWNLOAD_AS",
        //                         "MANAGE_SECURITY_SETTING",
        //                         "MOVE_DENTRY",
        //                         "RENAME_DENTRY",
        //                         "EXPORT_IMAGE",
        //                         "CREATE_CHILD",
        //                         "CONTENT_COPY",
        //                         "SAVE_AS_QUICK_LINK",
        //                         "RECOVER_DENTRY",
        //                         "PREVIEW",
        //                         "CLOUD_PRINT"
        //                     ],
        //                     "hasForbidden":false,
        //                     "roleId":"5000",
        //                     "roles":[
        //                         {
        //                             "code":"5000"
        //                         }
        //                     ]
        //                 }
        //             }
        //         ],
        //         "corpId":"ding3d99cda18de6e0d035c2f4657eb6378f",
        //         "createdTime":1624848955461,
        //         "creator":{
        //             "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //             "loginUserType":0,
        //             "name":"范雪蛟",
        //             "uid":"185916079"
        //         },
        //         "dentryId":"JaYr98zn2zLxnd6W",
        //         "dentryKey":"d7XA4w4olu92M34N",
        //         "dentryStatistic":{
        //             "childrenCount":0
        //         },
        //         "dentryType":"folder",
        //         "dentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //         "depth":0,
        //         "driveDentryId":"37483966289",
        //         "driveSceneType":"orgBizMeta",
        //         "driveSpaceId":"2823535130",
        //         "hasChildren":true,
        //         "hasMore":false,
        //         "illegal":false,
        //         "isInTrash":false,
        //         "loadMoreId":"pos:2048.0",
        //         "name":"#ROOT#",
        //         "orgId":"93255011",
        //         "positionCursor":"pos:65536.0",
        //         "root":true,
        //         "securityInfo":{
        //             "forbiddenCopy":{
        //                 "isInherit":true,
        //                 "name":"forbiddenCopy",
        //                 "value":false
        //             },
        //             "forbiddenSpread":{
        //                 "isInherit":true,
        //                 "name":"forbiddenSpread",
        //                 "value":false
        //             },
        //             "watermark":{
        //                 "isInherit":false,
        //                 "name":"watermark",
        //                 "value":false
        //             }
        //         },
        //         "shareScopeInfo":{
        //             "scope":0
        //         },
        //         "spaceId":"E0VzgyD5ylldmJep",
        //         "spaceProfile":{
        //             "createdTime":1624848955461,
        //             "description":"",
        //             "driveSpaceId":"2823535130",
        //             "icon":"",
        //             "id":"E0VzgyD5ylldmJep",
        //             "name":"mine space",
        //             "owner":{
        //                 "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //                 "name":"范雪蛟",
        //                 "uid":"185916079"
        //             },
        //             "rootDentryUuid":"amweZ92PV6yq1naQc4LpwpNRWxEKBD6p",
        //             "type":2,
        //             "updatedTime":1717571647394
        //         },
        //         "thumbnail":"",
        //         "updatedTime":1717571647394,
        //         "updator":{
        //             "avatorMediaId":"@lQLPD2_UPzN8aGHNAhzNAhywz4BzVv2LHHgF-krn8tH5AA",
        //             "loginUserType":0,
        //             "name":"范雪蛟",
        //             "uid":"185916079"
        //         },
        //         "url":{
        //
        //         },
        //         "visitorRelatedInfo":{
        //             "dentryActions":[
        //                 "COPY_DENTRY",
        //                 "GET_DENTRY_MEMBER",
        //                 "GET_DENTRY",
        //                 "MANAGE_DENTRY_MEMBER",
        //                 "DELETE_DENTRY",
        //                 "MANAGE_SECURITY_SETTING",
        //                 "UPLOAD_FOLDER",
        //                 "MOVE_DENTRY",
        //                 "RENAME_DENTRY",
        //                 "IMPORT",
        //                 "CHANGE_PERMISSION_MODE",
        //                 "CREATE_CHILD",
        //                 "PUBLIC_SHARE",
        //                 "IMPORT_FOLDER",
        //                 "LINK_SHARE",
        //                 "SAVE_AS_QUICK_LINK",
        //                 "UPLOAD",
        //                 "LIST_CHILD",
        //                 "SAVE_AS",
        //                 "TEMPORARY_SHARE_NODE",
        //                 "RECYCLE_DENTRY",
        //                 "RECOVER_DENTRY",
        //                 "PREVIEW"
        //             ],
        //             "hasForbidden":false,
        //             "roleId":"5000",
        //             "roles":[
        //                 {
        //                     "code":"5000"
        //                 }
        //             ]
        //         }
        //     })
        // }, 5000)
    },
    methods: {
        readCurrentPage() {
            this.$refs.progressTip.classList.remove("text-error");
            this.$refs.progressTip.textContent = "正在读取当前页面...";
            this.$refs.progress.classList.remove("hidden");
            this.$refs.reloadBtn.classList.add("hidden");

            let href = window.location.href;
            if (href.indexOf(DingTalkDomain) === -1) {
                // 不在钉钉文档界面
                this.$refs.progressTip.classList.add("text-error");
                this.$refs.progressTip.textContent = "读取失败，当前页面不是钉钉文档页面。请打开钉钉文档页面后再打开本工具。";
                this.$refs.progress.classList.add("hidden");
                this.$emit("notdd");
                return;
            }

            // 打开了某个文件或目录
            if (href.includes("/i/nodes/")) {
                let dentryId = window.location.pathname.split("/").pop()
                this.getDocInfoAndChild(dentryId);
                return;
            }

            // 打开了自己的空间
            if (href.includes("/i/desktop/my-space")) {
                this.getMySpaceInfo();
                return;
            }

            // 打开了指定的空间
            if (href.includes("/i/spaces/")) {
                let spaceId = href.replace(/\/?overview/g, "").split("/").pop().trim();
                this.getSpaceInfo(spaceId);
                return;
            }

            // 没有打开任何地方
            this.$refs.progressTip.classList.remove("text-error");
            this.$refs.progressTip.textContent = "请打开某个知识库之后再运行本工具。";
            this.$refs.progress.classList.add("hidden");
            this.$refs.reloadBtn.classList.remove("hidden");
        },
        reload() {
            this.readCurrentPage();
        },
        async onDownloadClick() {
            let allDi = this.$refs.di;
            if (!allDi) {
                return;
            }
            if (!Array.isArray(allDi)) {
                allDi = [allDi];
            }

            try {
                // 先让用户选择一个目录保存。
                const dirHandle = await window.showDirectoryPicker();

                for (let i = 0; i < allDi.length; i++) {
                    await allDi[i].$download(dirHandle);
                }
            }catch (e) {
                dalert("出错", `下载出错了：${e.message}`);
            }

        },
        onDentrySelectChange(arg) {
            let dentry = arg.data;
            let selected = arg.selected;
            let index = this.selecteds.findIndex(sel => {
                return sel[sel.length - 1].dentryUuid === arg.data[arg.data.length - 1].dentryUuid;
            });

            if (index === -1 && selected) {
                this.selecteds.push(dentry);
            } else if(index !== -1 && !selected) {
                this.selecteds.splice(index, 1);
            }
        },
        async getDocInfoAndChild(dentryUuid) {
            const {data} = await getDocList(dentryUuid);
            this.$refs.progressTip.textContent = data.name;
            this.$refs.progress.classList.add("hidden");
            this.addDentry(data);
            this.$refs.list.classList.remove("hidden");
            this.$refs.downloadBtn.classList.remove("hidden");
        },
        async getMySpaceInfo() {
            const {data} = await getSpaceInfo();
            await this.getDocInfoAndChild(data.rootDentryUuid);
        },
        async getSpaceInfo(spaceId) {
            const {data} = await getSpaceInfo(spaceId);
            this.$refs.progressTip.textContent = data.name;
            await this.getDocInfoAndChild(data.rootDentryUuid);
        },
        addDentry(dentryInfo) {
            this.dentrys.push(dentryInfo);
            this.$refs.list.append(this.$createElement(h => {
                return h("DentryItem", {ref: "di", props: () => ({dentryInfo: dentryInfo}), on: {selectChange: this.onDentrySelectChange}})
            }))
        }
    },
    data: {
        accessToken: "",
        selecteds: [],
        dentrys: [

        ],
    }
}
